name: Build and Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with Java ${{ matrix.java }}
    
    strategy:
      matrix:
        java: [8, 11, 17, 21]
        
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Run tests
      run: mvn clean test
      
    - name: Run checkstyle
      run: mvn checkstyle:check || true
      
  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release'
    
    strategy:
      matrix:
        platform:
          - name: "GitHub"
            artifact: "mccore-${{ github.event.release.tag_name }}.jar"
          - name: "Spigot" 
            artifact: "mccore-spigot-${{ github.event.release.tag_name }}.jar"
          - name: "Bukkit"
            artifact: "mccore-bukkit-${{ github.event.release.tag_name }}.jar"
          - name: "Modrinth"
            artifact: "mccore-modrinth-${{ github.event.release.tag_name }}.jar"
    
    name: Build for ${{ matrix.platform.name }}
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
      
    - name: Rename artifact for ${{ matrix.platform.name }}
      run: |
        mkdir -p artifacts
        cp target/mccore-*.jar artifacts/${{ matrix.platform.artifact }}
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform.name }}-build
        path: artifacts/${{ matrix.platform.artifact }}
        
  publish-github:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Publish to GitHub Packages
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  publish-release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v5
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
        
    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/GitHub-build/*.jar
          artifacts/Spigot-build/*.jar
          artifacts/Bukkit-build/*.jar
          artifacts/Modrinth-build/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}