# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
  pull_request:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'adopt'
          java-version: '17'


      - if: github.event.release
        name: Update version in pom.xml (Release only)
        run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false

      - name: Build with Maven
        run: |
          mvn package
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "git_hash=$git_hash" >> $GITHUB_ENV
          echo "artifactPath=$(pwd)/target" >> $GITHUB_ENV

      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project

      - name: Upload Plugin jar if master
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v3
        with:
          name: mccore-${{ env.snapshotVersion }}-${{ env.git_hash }}.jar
          path: ${{ env.artifactPath }}/mccore-${{ steps.project.outputs.version }}.jar

      - name: Upload Plugin jar if not master
        if: github.ref != 'refs/heads/master'
        uses: actions/upload-artifact@v3
        with:
          name: mccore-${{ env.snapshotVersion }}-${{ steps.extract_branch.outputs.branch }}-${{ env.git_hash }}.jar
          path: ${{ env.artifactPath }}/mccore-${{ steps.project.outputs.version }}.jar

      - name: Nexus Repo Publish master
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        if: github.ref == 'refs/heads/master'
        with:
          serverUrl: https://repo.thedutchruben.nl/
          username: admin
          password: ${{ secrets.SONAR_TOKEN }}
          format: maven2
          repository: maven-releases
          coordinates: groupId=nl.thedutchruben artifactId=mccore version=${{ steps.project.outputs.version }}
          assets: extension=jar
          filename: ./mccore-${{ steps.project.outputs.version }}.jar

      - name: Nexus Repo Publish not master
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        if: github.ref != 'refs/heads/master'
        with:
          serverUrl: https://repo.thedutchruben.nl/
          username: admin
          password: ${{ secrets.SONAR_TOKEN }}
          format: maven2
          repository: maven-releases
          coordinates: groupId=nl.thedutchruben artifactId=mccore version=${{ steps.project.outputs.version }}-${{ steps.extract_branch.outputs.branch }}
          assets: extension=jar
          filename: ./mccore-${{ steps.project.outputs.version }}.jar
      - name: send message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          file: ${{ env.artifactPath }}/mccore-${{ steps.project.outputs.version }}.jar
          message: "New McCore Release: ${{ steps.project.outputs.version }}"
          color: "#48f442"
          username: "McCore Release"