name: Discord Notification

on: [push,pull_request,fork,pull_request_review,pull_request_review_comment,issue_comment,issues]

jobs:
  report-status:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Java JDK 11
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'adopt'
          java-version: '11'
          java-package: jdk
          architecture: x64
      - name: Run Discord Webhook
        uses: baked-libs/discord-webhook@main
        with:
          id: ${{ secrets.DISCORD_NOTIFICATION_ID }}
          token: ${{ secrets.DISCORD_NOTIFICATION_TOKEN }}
